-- =============================================
-- 11_MEDALLION_ARCHITECTURE.SQL
-- Healthcare RxDecision Analytics Platform
-- Data Source: Snowflake Marketplace (Definitive Healthcare)
-- All tables under 5K records for minimal credit usage
-- =============================================

USE ROLE ACCOUNTADMIN;

-- =============================================
-- BRONZE LAYER (RAW_DB)
-- =============================================
USE DATABASE RAW_DB;
USE SCHEMA RAW_SCHEMA;
USE WAREHOUSE COMPUTE_WH;

-- Patient Raw Table (2,000 records seeded from marketplace HCP)
CREATE OR REPLACE TABLE PATIENT_RAW AS
WITH MARKETPLACE_SEED AS (
    SELECT FIRST_NAME, LAST_NAME, GENDER, CITY, STATE, ZIP, PRIMARY_SPECIALTY,
        ROW_NUMBER() OVER (ORDER BY HCP_NPI) AS RN
    FROM RXDECISION_INSIGHTS_PRESCRIPTION_THERAPY_DECISIONS_SAMPLE.SAMPLES.REF_HCP_BY_NPI
),
GENERATED AS (SELECT SEQ4() + 1 AS ID FROM TABLE(GENERATOR(ROWCOUNT => 2000)))
SELECT
    'P' || LPAD(g.ID::STRING, 5, '0') AS PATIENT_ID,
    s.FIRST_NAME || ' ' || s.LAST_NAME AS NAME,
    UNIFORM(18, 90, RANDOM()) AS AGE, s.GENDER,
    DATEADD(DAY, -UNIFORM(1, 365, RANDOM()), CURRENT_DATE()) AS ADMISSION_DATE,
    CASE UNIFORM(1, 6, RANDOM()) WHEN 1 THEN 'Cardiology' WHEN 2 THEN 'Neurology'
        WHEN 3 THEN 'Orthopedics' WHEN 4 THEN 'Psychiatry' WHEN 5 THEN 'Family Medicine' ELSE 'General' END AS DIAGNOSIS
FROM GENERATED g JOIN MARKETPLACE_SEED s ON s.RN = MOD(g.ID - 1, 100) + 1;

-- Hospitals (marketplace HCO)
CREATE OR REPLACE TABLE HOSPITALS AS
SELECT h.HCO_NPI AS FACILITY_NPI, h.ORG_NAME AS HOSPITAL_NAME, h.CITY, h.STATE, h.ZIP, h.PHONE, h.DEFINITIVE_ID,
    f.NUMBER_BEDS, f.NET_PATIENT_REVENUE, f.TOTAL_PATIENT_REVENUE, f.NET_INCOME, f.YEAR AS FINANCIAL_YEAR
FROM RXDECISION_INSIGHTS_PRESCRIPTION_THERAPY_DECISIONS_SAMPLE.SAMPLES.REF_HCO_BY_NPI h
LEFT JOIN RXDECISION_INSIGHTS_PRESCRIPTION_THERAPY_DECISIONS_SAMPLE.SAMPLES.REF_HCO_FINANCIAL_AND_CLINICAL_METRICS f
    ON h.DEFINITIVE_ID = f.DEFINITIVE_ID;

-- HCO Locations (marketplace)
CREATE OR REPLACE TABLE HCO_LOCATIONS AS
SELECT * FROM RXDECISION_INSIGHTS_PRESCRIPTION_THERAPY_DECISIONS_SAMPLE.SAMPLES.REF_HCO_LOCATIONS_BY_DEFINITIVE_ID;

-- Provider Affiliations (marketplace)
CREATE OR REPLACE TABLE PROVIDER_AFFILIATIONS AS
SELECT * FROM RXDECISION_INSIGHTS_PRESCRIPTION_THERAPY_DECISIONS_SAMPLE.SAMPLES.AFFILIATIONS_HCP_HCO_BY_NPI_ACTIVE;

-- Prescription Data (marketplace Rx)
CREATE OR REPLACE TABLE PRESCRIPTION_DATA AS
SELECT r.CLAIM_YEAR, r.PRODUCT AS MEDICATION_NAME, r.HCP_NPI AS PRESCRIBER_NPI,
    r.RX_EVENT_TYPE, r.RX_EVENT_CLAIMS, r.RX_TOTAL_CLAIMS, r.RX_EVENT_SCORE_DECILE,
    n.NRX_COUNT AS NEW_RX_COUNT, n.TRX_COUNT AS TOTAL_RX_COUNT, r.DATE_UPDATED
FROM RXDECISION_INSIGHTS_PRESCRIPTION_THERAPY_DECISIONS_SAMPLE.SAMPLES.RX_PRODUCT_DECISIONS_YEARLY r
LEFT JOIN RXDECISION_INSIGHTS_PRESCRIPTION_THERAPY_DECISIONS_SAMPLE.SAMPLES.NRX_TRX_YEARLY n ON r.HCP_NPI = n.HCP_NPI;

-- ICU Events (4,000 records)
CREATE OR REPLACE TABLE ICU_EVENTS AS
SELECT 'E' || LPAD(SEQ4()::STRING, 6, '0') AS EVENT_ID,
    'P' || LPAD(MOD(ABS(RANDOM()), 2000)::STRING, 5, '0') AS PATIENT_ID,
    CASE MOD(ABS(RANDOM()), 5) WHEN 0 THEN 'Vitals Check' WHEN 1 THEN 'Medication' WHEN 2 THEN 'Procedure' WHEN 3 THEN 'Alert' ELSE 'Transfer' END AS EVENT_TYPE,
    DATEADD(HOUR, -MOD(ABS(RANDOM()), 720), CURRENT_TIMESTAMP()) AS EVENT_TIMESTAMP,
    50 + MOD(ABS(RANDOM()), 101) AS HEART_RATE,
    80 + MOD(ABS(RANDOM()), 21) AS OXYGEN_LEVEL
FROM TABLE(GENERATOR(ROWCOUNT => 4000));

-- Billing Data (3,000 records)
CREATE OR REPLACE TABLE BILLING_DATA AS
SELECT 'B' || LPAD(SEQ4()::STRING, 6, '0') AS BILL_ID,
    'P' || LPAD(MOD(ABS(RANDOM()), 2000)::STRING, 5, '0') AS PATIENT_ID,
    ROUND(1000 + UNIFORM(0, 99000, RANDOM()), 2) AS AMOUNT,
    DATEADD(DAY, -MOD(ABS(RANDOM()), 365), CURRENT_DATE()) AS BILL_DATE,
    CASE MOD(ABS(RANDOM()), 3) WHEN 0 THEN 'PAID' WHEN 1 THEN 'PENDING' ELSE 'OVERDUE' END AS STATUS
FROM TABLE(GENERATOR(ROWCOUNT => 3000));

-- =============================================
-- SILVER LAYER (TRANSFORM_DB)
-- =============================================
USE DATABASE TRANSFORM_DB;
USE SCHEMA TRANSFORM_SCHEMA;

CREATE OR REPLACE TABLE CLEAN_PATIENT AS
SELECT PATIENT_ID, NAME, AGE, GENDER, ADMISSION_DATE, DIAGNOSIS,
    LEFT(PATIENT_ID, 2) || '***' AS PATIENT_ID_MASKED, CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.PATIENT_RAW;

CREATE OR REPLACE TABLE CLEAN_ICU_EVENTS AS
SELECT EVENT_ID, PATIENT_ID, EVENT_TYPE, EVENT_TIMESTAMP, HEART_RATE, OXYGEN_LEVEL,
    CASE WHEN HEART_RATE < 60 OR HEART_RATE > 100 OR OXYGEN_LEVEL < 92 THEN TRUE ELSE FALSE END AS IS_CRITICAL,
    CURRENT_TIMESTAMP() AS ETL_TIMESTAMP
FROM RAW_DB.RAW_SCHEMA.ICU_EVENTS;

-- =============================================
-- GOLD LAYER (ANALYTICS_DB)
-- =============================================
USE DATABASE ANALYTICS_DB;
USE SCHEMA ANALYTICS_SCHEMA;

CREATE OR REPLACE TABLE PATIENT_ANALYTICS AS
SELECT p.PATIENT_ID, p.NAME, p.AGE, p.GENDER, p.ADMISSION_DATE, p.DIAGNOSIS,
    COUNT(e.EVENT_ID) AS ICU_EVENT_COUNT, AVG(e.HEART_RATE) AS AVG_HEART_RATE,
    AVG(e.OXYGEN_LEVEL) AS AVG_OXYGEN_LEVEL,
    SUM(CASE WHEN e.IS_CRITICAL THEN 1 ELSE 0 END) AS CRITICAL_EVENT_COUNT
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT p
LEFT JOIN TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS e ON p.PATIENT_ID = e.PATIENT_ID
GROUP BY p.PATIENT_ID, p.NAME, p.AGE, p.GENDER, p.ADMISSION_DATE, p.DIAGNOSIS;

CREATE OR REPLACE TABLE BILLING_ANALYTICS AS
SELECT PATIENT_ID, COUNT(*) AS TOTAL_BILLS, SUM(AMOUNT) AS TOTAL_AMOUNT, AVG(AMOUNT) AS AVG_BILL_AMOUNT,
    SUM(CASE WHEN STATUS = 'PAID' THEN AMOUNT ELSE 0 END) AS PAID_AMOUNT,
    SUM(CASE WHEN STATUS = 'PENDING' THEN AMOUNT ELSE 0 END) AS PENDING_AMOUNT,
    SUM(CASE WHEN STATUS = 'OVERDUE' THEN AMOUNT ELSE 0 END) AS OVERDUE_AMOUNT
FROM RAW_DB.RAW_SCHEMA.BILLING_DATA GROUP BY PATIENT_ID;
