-- =============================================
-- 13_AI_READY_LAYER.SQL
-- Healthcare RxDecision Analytics Platform
-- Under 5K records per table
-- =============================================

USE ROLE ACCOUNTADMIN;
USE DATABASE AI_READY_DB;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS FEATURE_STORE COMMENT = 'ML Feature Store';
USE SCHEMA FEATURE_STORE;

CREATE OR REPLACE TABLE ICU_FEATURE_STORE AS
SELECT e.PATIENT_ID, p.AGE, p.GENDER, p.DIAGNOSIS,
    COUNT(*) AS TOTAL_EVENTS,
    SUM(CASE WHEN e.IS_CRITICAL THEN 1 ELSE 0 END) AS CRITICAL_EVENTS,
    AVG(e.HEART_RATE) AS AVG_HEART_RATE, MIN(e.HEART_RATE) AS MIN_HEART_RATE,
    MAX(e.HEART_RATE) AS MAX_HEART_RATE, STDDEV(e.HEART_RATE) AS STD_HEART_RATE,
    AVG(e.OXYGEN_LEVEL) AS AVG_OXYGEN, MIN(e.OXYGEN_LEVEL) AS MIN_OXYGEN,
    MAX(e.OXYGEN_LEVEL) AS MAX_OXYGEN, STDDEV(e.OXYGEN_LEVEL) AS STD_OXYGEN,
    DATEDIFF(DAY, MIN(e.EVENT_TIMESTAMP), MAX(e.EVENT_TIMESTAMP)) AS ICU_STAY_DAYS,
    ROUND(SUM(CASE WHEN e.IS_CRITICAL THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS CRITICAL_EVENT_RATE,
    CASE WHEN AVG(e.OXYGEN_LEVEL) < 90 OR AVG(e.HEART_RATE) > 110 THEN 'HIGH'
         WHEN AVG(e.OXYGEN_LEVEL) < 94 OR AVG(e.HEART_RATE) > 100 THEN 'MEDIUM'
         ELSE 'LOW' END AS RISK_SCORE,
    CURRENT_TIMESTAMP() AS FEATURE_TIMESTAMP
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_ICU_EVENTS e
JOIN TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT p ON e.PATIENT_ID = p.PATIENT_ID
GROUP BY e.PATIENT_ID, p.AGE, p.GENDER, p.DIAGNOSIS;

CREATE OR REPLACE TABLE PATIENT_NOTES AS
SELECT 'N' || LPAD(SEQ4()::STRING, 6, '0') AS NOTE_ID,
    'P' || LPAD(MOD(ABS(RANDOM()), 2000)::STRING, 5, '0') AS PATIENT_ID,
    CASE MOD(ABS(RANDOM()), 5)
        WHEN 0 THEN 'Patient presents with chest pain and shortness of breath. ECG shows normal sinus rhythm.'
        WHEN 1 THEN 'Follow-up visit for diabetes management. Blood sugar levels improving with current medication.'
        WHEN 2 THEN 'Post-operative day 2. Wound healing well. No signs of infection.'
        WHEN 3 THEN 'Patient reports dizziness and fatigue. Ordered blood work to check for anemia.'
        ELSE 'Routine checkup. All vitals within normal range. Continue current treatment plan.' END AS NOTE_TEXT,
    DATEADD(DAY, -MOD(ABS(RANDOM()), 90), CURRENT_DATE()) AS NOTE_DATE,
    CASE MOD(ABS(RANDOM()), 4) WHEN 0 THEN 'Progress Note' WHEN 1 THEN 'Discharge Summary' WHEN 2 THEN 'Consultation' ELSE 'Lab Results' END AS NOTE_TYPE
FROM TABLE(GENERATOR(ROWCOUNT => 2000));

CREATE OR REPLACE TABLE PATIENT_EMBEDDINGS AS
SELECT PATIENT_ID,
    ARRAY_CONSTRUCT(UNIFORM(0::FLOAT,1::FLOAT,RANDOM()),UNIFORM(0::FLOAT,1::FLOAT,RANDOM()),
        UNIFORM(0::FLOAT,1::FLOAT,RANDOM()),UNIFORM(0::FLOAT,1::FLOAT,RANDOM()),
        UNIFORM(0::FLOAT,1::FLOAT,RANDOM()),UNIFORM(0::FLOAT,1::FLOAT,RANDOM()),
        UNIFORM(0::FLOAT,1::FLOAT,RANDOM()),UNIFORM(0::FLOAT,1::FLOAT,RANDOM())) AS EMBEDDING_VECTOR,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM TRANSFORM_DB.TRANSFORM_SCHEMA.CLEAN_PATIENT;

CREATE SCHEMA IF NOT EXISTS SEMANTIC_MODELS COMMENT = 'Cortex Analyst Semantic Models';

SELECT 'ICU_FEATURE_STORE' AS TABLE_NAME, COUNT(*) AS RECORDS FROM AI_READY_DB.FEATURE_STORE.ICU_FEATURE_STORE
UNION ALL SELECT 'PATIENT_NOTES', COUNT(*) FROM AI_READY_DB.FEATURE_STORE.PATIENT_NOTES
UNION ALL SELECT 'PATIENT_EMBEDDINGS', COUNT(*) FROM AI_READY_DB.FEATURE_STORE.PATIENT_EMBEDDINGS;
