/*=============================================================================
  GITHUB_INTEGRATION.SQL
  Healthcare RxDecision Analytics Platform
  Snowflake <-> GitHub Connection

  Account:  tyb42779
  Username: DEVIKAPG
  GitHub:   Devikapgdevi
  Repo:     Healthcare-RxDecision-Analytics-Platform
=============================================================================*/

USE ROLE ACCOUNTADMIN;

-- STEP 1: DATABASE & SCHEMA
CREATE DATABASE IF NOT EXISTS INTEGRATIONS_DB;
CREATE SCHEMA IF NOT EXISTS INTEGRATIONS_DB.GIT;
USE DATABASE INTEGRATIONS_DB;
USE SCHEMA GIT;

-- STEP 2: GITHUB PAT SECRET
-- IMPORTANT: Do NOT store PAT tokens in plain text. 
-- Create the secret manually via Snowsight or a secure session:
--   CREATE SECRET IF NOT EXISTS GITHUB_PAT_SECRET
--     TYPE = PASSWORD
--     USERNAME = 'Devikapgdevi'
--     PASSWORD = '<YOUR_GITHUB_PAT>';
--
-- To update an existing secret:
--   ALTER SECRET GITHUB_PAT_SECRET SET PASSWORD = '<YOUR_NEW_PAT>';
--
-- Verify the secret exists:
DESCRIBE SECRET GITHUB_PAT_SECRET;

-- STEP 3: API INTEGRATION
CREATE OR REPLACE API INTEGRATION GITHUB_API_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/Devikapgdevi')
  ALLOWED_AUTHENTICATION_SECRETS = (INTEGRATIONS_DB.GIT.GITHUB_PAT_SECRET)
  ENABLED = TRUE;

-- STEP 4: CONNECT REPOSITORY
USE DATABASE INTEGRATIONS_DB;
USE SCHEMA GIT;
CREATE OR REPLACE GIT REPOSITORY INTEGRATIONS_DB.GIT.HEALTHCARE_ENTERPRISE_REPO
  API_INTEGRATION = GITHUB_API_INTEGRATION
  GIT_CREDENTIALS = INTEGRATIONS_DB.GIT.GITHUB_PAT_SECRET
  ORIGIN = 'https://github.com/Devikapgdevi/Healthcare-RxDecision-Analytics-Platform';

-- STEP 5: GRANT PERMISSIONS
GRANT USAGE ON DATABASE INTEGRATIONS_DB TO ROLE HC_ACCOUNT_ADMIN;
GRANT USAGE ON SCHEMA INTEGRATIONS_DB.GIT TO ROLE HC_ACCOUNT_ADMIN;
GRANT USAGE ON INTEGRATION GITHUB_API_INTEGRATION TO ROLE HC_ACCOUNT_ADMIN;
GRANT READ, WRITE ON GIT REPOSITORY HEALTHCARE_ENTERPRISE_REPO TO ROLE HC_ACCOUNT_ADMIN;

GRANT USAGE ON DATABASE INTEGRATIONS_DB TO ROLE HC_DATA_ENGINEER;
GRANT USAGE ON SCHEMA INTEGRATIONS_DB.GIT TO ROLE HC_DATA_ENGINEER;
GRANT READ, WRITE ON GIT REPOSITORY HEALTHCARE_ENTERPRISE_REPO TO ROLE HC_DATA_ENGINEER;

GRANT USAGE ON DATABASE INTEGRATIONS_DB TO ROLE HC_ANALYST;
GRANT USAGE ON SCHEMA INTEGRATIONS_DB.GIT TO ROLE HC_ANALYST;
GRANT READ ON GIT REPOSITORY HEALTHCARE_ENTERPRISE_REPO TO ROLE HC_ANALYST;

-- STEP 6: FETCH & VERIFY
ALTER GIT REPOSITORY HEALTHCARE_ENTERPRISE_REPO FETCH;
SHOW GIT BRANCHES IN HEALTHCARE_ENTERPRISE_REPO;
DESCRIBE GIT REPOSITORY HEALTHCARE_ENTERPRISE_REPO;
